Prints info from env, runs conjur

diff --git a/script/variable b/script/variable
--- a/script/variable
+++ b/script/variable
@@ -3,21 +3,55 @@
 # interactively build conjur variable creation command
 # copyright 2015 Ryan Prior all rights reserved
 
-# get defaults
-kind_default="secret" # TODO read this from somewhere
+#readi () {
+#    printf "\n%s\nExample: %s\n" "$1" "$2"
+#    if [-z "$3" ]; then echo "This field is required."; fi
 
+req () { echo "This field is required."; }
+
+echo $_cj_variable_create_desc
+echo $_cj_variable_desc
+
+printf "\n%s\nExample: %s\n" "$_cj_id_desc" "$_cj_id_example"
+if ! [ -v _cj_id_default ]; then req; fi
 # prompt for ID
 read -e -p "ID: " id
+# set default
+if [ -v _cj_id_default ] && [ -z $id ]; then
+    id=$_cj_id_default
+fi
 
+printf "\n%s\nExample: %s\n" "$_cj_group_desc" "$_cj_group_example"
+if ! [ -v _cj_group_default ]; then
+    req
+else
+    if [ -z $_cj_group_default ]; then
+	group_prompt_default=" (default none)"
+    else
+	printf -v group_prompt_default " (default %s)" "$_cj_group_default"
+    fi
+fi
 # prompt for group
-read -e -p "group: " group
+read -e -p "group:$group_prompt_default " group
+# set default
+if [ -v _cj_group_default ] && [ -z $group ]; then
+    group=$_cj_group_default
+fi
 
+printf "\n%s\nExample: %s\n" "$_cj_kind_desc" "$_cj_kind_example"
+if ! [ -v _cj_kind_default ]; then req; fi
 # prompt for kind
-read -e -p "kind: " kind
+read -e -p "kind: (default $_cj_kind_default) " kind
+# set default
+if [ -v _cj_kind_default ] && [ -z $kind ]; then
+    kind=$_cj_kind_default
+fi
 
+printf "\n%s\nExample: %s\n" "$_cj_mimetype_desc" "$_cj_mimetype_example"
 # prompt for mime-type
 echo "Choose or enter a mime-type"
-select mimetype in "application/json" \
+select mimetype in "text/plain" \
+		   "application/json" \
                    "application/xml" \
                    "application/x-yaml" \
                    "application/x-pem-file" \
@@ -28,12 +62,9 @@ select mimetype in "application/json" \
     esac
 done
 
-# prompt for annotations
-echo "annotation:"
-while IFS= read -re line; do
-    annotation=$(printf '%s\n%s' "$annotation" "$line")
-done
+# TODO allow prompt for interactive annotations
 
+printf "\n%s\nExample: %s\nSend EOF (ctrl+d) when finished\n" "$_cj_value_desc" $"_cj_value_example"
 # prompt for value
 echo "value:"
 while IFS= read -re line; do
@@ -41,22 +72,25 @@ while IFS= read -re line; do
 done
 
 # prompt to confirm
+echo "group $group kind $kind type $mimetype value $value id $id"
+if [ "$group" ]; then printf -v group $'\n  --as-group="%s"\\' "$group"; fi
+if [ "$value" ]; then printf -v value $'\n  --value="%s"\\' "$value"; fi
+printf -v command 'conjur variable create\%s
+  --kind="%s"\
+  --mime-type="%s"\%s
+  "%s"' "$group" "$kind" "$mimetype" "$value" "$id"
+
 printf '
 CONFIRMATION
 ---
-conjur variable create\
-  --annotate\
-  --kind=%s\
-  --mime-type=%s\
-  --value=%s
 %s
 ---
-' "$kind" "$mimetype" "$value" "$annotation"
+' "$command"
 
 while true; do
     read -e -p "Run command now? (Y/N) " correct
     case $correct in
-        [Yy]* ) echo "OK"; break;; # TODO run command
+        [Yy]* ) eval $command; break;;
         [Nn]* ) echo "quit"; exit 1;;
         *     ) echo "Enter Y or N";;
     esac
